### ISSUE TITLE
MIT license

### ISSUE THREAD

**Issue by unicomp21** [madmurphy/stringview.js#2]
Any chance we can get an MIT license?  I'd like to port this to dart.

**Comment by madmurphy** [comment]
@unicomp21

Thank you for the interest. But unfortunately I find the MIT license quite primitive, both for the users -- because it does not grant that all the efforts spent on an intellectual work will always remain free -- and for the programmers -- because it does not grant that anybody will capitalize their work without sharing their purpose.
