### ISSUE TITLE
Checking for 6 bytes instead of 4 bytes in loadUTF8CharCode

### ISSUE THREAD

**Issue by topicus** [madmurphy/stringview.js#6]
If I'm not wrong utf8 char codes span 4 bytes at most. Is there any reason to check for 6 bytes?

https://github.com/madmurphy/stringview.js/blob/master/stringview.js#L325

The same applies to putUTF8CharCode
https://github.com/madmurphy/stringview.js/blob/master/stringview.js#L341

**Comment by madmurphy** [comment]
@topicus The ISO 10646 view of UTF-8 considers valid codepoints encoded by 1-6 bytes, while the Unicode view of UTF-8 in 2003 has limited it to 1-4 bytes (in order to match UTF-16's codepoints). In this situation a UTF-8 interpreter in front of a 6-byte sequence has two possibilities: consider it invalid or try to encode it in any case. StringView chooses the second one. This is what I considered a good compromise. But if you have good arguments against it I am interested!

**Comment by madmurphy** [comment]
@topicus The ISO 10646 view of UTF-8 considers valid codepoints encoded by 1-6 bytes, while the Unicode view of UTF-8 in 2003 has limited them to 1-4 bytes (in order to match UTF-16's codepoints). In this situation a UTF-8 interpreter in front of a 5/6-byte sequence has two possibilities: consider it invalid or try to encode it in any case. StringView chooses the second one. This is what I considered a good compromise, but if you have good arguments against it I am interested!

**Comment by topicus** [comment]
@madmurphy you are ok, performance gain is very small.

**Comment by topicus** [comment]
I've created a PR to add a comment to flag this. https://github.com/madmurphy/stringview.js/pull/7
